//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ApplicationData.Implementation
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ApplicationDataObjectContext : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ApplicationDataObjectContext”部分中的连接字符串初始化新 ApplicationDataObjectContext 对象。
        /// </summary>
        public ApplicationDataObjectContext() : base("name=ApplicationDataObjectContext", "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ApplicationDataObjectContext 对象。
        /// </summary>
        public ApplicationDataObjectContext(string connectionString) : base(connectionString, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ApplicationDataObjectContext 对象。
        /// </summary>
        public ApplicationDataObjectContext(EntityConnection connection) : base(connection, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Table1Item> Table1ItemSet
        {
            get
            {
                if ((_Table1ItemSet == null))
                {
                    _Table1ItemSet = base.CreateObjectSet<Table1Item>("Table1ItemSet");
                }
                return _Table1ItemSet;
            }
        }
        private ObjectSet<Table1Item> _Table1ItemSet;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Table2Item> Table2ItemSet
        {
            get
            {
                if ((_Table2ItemSet == null))
                {
                    _Table2ItemSet = base.CreateObjectSet<Table2Item>("Table2ItemSet");
                }
                return _Table2ItemSet;
            }
        }
        private ObjectSet<Table2Item> _Table2ItemSet;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Table1ItemSet EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTable1ItemSet(Table1Item table1Item)
        {
            base.AddObject("Table1ItemSet", table1Item);
        }
    
        /// <summary>
        /// 用于向 Table2ItemSet EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTable2ItemSet(Table2Item table2Item)
        {
            base.AddObject("Table2ItemSet", table2Item);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Table1Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Table1Item : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Table1Item 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="rowVersion">RowVersion 属性的初始值。</param>
        public static Table1Item CreateTable1Item(global::System.Int32 id, global::System.Byte[] rowVersion)
        {
            Table1Item table1Item = new Table1Item();
            table1Item.Id = id;
            table1Item.RowVersion = rowVersion;
            return table1Item;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Table2Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Table2Item : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Table2Item 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="rowVersion">RowVersion 属性的初始值。</param>
        public static Table2Item CreateTable2Item(global::System.Int32 id, global::System.Byte[] rowVersion)
        {
            Table2Item table2Item = new Table2Item();
            table2Item.Id = id;
            table2Item.RowVersion = rowVersion;
            return table2Item;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
    }

    #endregion

    
}
