//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// 提供要对 LightAppData 数据源中的数据进行查询和更新的成员。
    /// </summary>
    public sealed partial class LightAppDataService
        : global::LightSwitchApplication.LightAppData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LightAppDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// 获取此应用程序的 Application 对象。Application 对象可提供对活动屏幕的访问权限、用于打开屏幕的方法以及对当前用户的访问权限。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// 获取包含数据工作区。该数据工作区可提供对应用程序中所有数据源的访问权限。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_Inserting(global::LightSwitchApplication.AccountItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_Inserted(global::LightSwitchApplication.AccountItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_Updating(global::LightSwitchApplication.AccountItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_Updated(global::LightSwitchApplication.AccountItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_Deleting(global::LightSwitchApplication.AccountItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_Deleted(global::LightSwitchApplication.AccountItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_Validate(global::LightSwitchApplication.AccountItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.AccountItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_Inserting(global::LightSwitchApplication.EventItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_Inserted(global::LightSwitchApplication.EventItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_Updating(global::LightSwitchApplication.EventItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_Updated(global::LightSwitchApplication.EventItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_Deleting(global::LightSwitchApplication.EventItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_Deleted(global::LightSwitchApplication.EventItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_Validate(global::LightSwitchApplication.EventItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.EventItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LightAppDataService, global::LightSwitchApplication.AccountItem>
                __AccountEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LightAppDataService, global::LightSwitchApplication.AccountItem>(
                    "Account",
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_CanInsert,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_CanUpdate,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_CanDelete,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_CanRead,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_Inserting,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_Inserted,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_Updating,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_Updated,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_Deleting,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_Deleted,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_Validate,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Account_Filter);
            private static bool __Account_CanInsert(global::LightSwitchApplication.LightAppDataService d)
            {
                bool result = true;
                d.Account_CanInsert(ref result);
                return result;
            }
            private static bool __Account_CanUpdate(global::LightSwitchApplication.LightAppDataService d)
            {
                bool result = true;
                d.Account_CanUpdate(ref result);
                return result;
            }
            private static bool __Account_CanDelete(global::LightSwitchApplication.LightAppDataService d)
            {
                bool result = true;
                d.Account_CanDelete(ref result);
                return result;
            }
            private static bool __Account_CanRead(global::LightSwitchApplication.LightAppDataService d)
            {
                bool result = true;
                d.Account_CanRead(ref result);
                return result;
            }
            private static void __Account_Inserting(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.AccountItem e)
            {
                d.Account_Inserting(e);
            }
            private static void __Account_Inserted(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.AccountItem e)
            {
                d.Account_Inserted(e);
            }
            private static void __Account_Updating(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.AccountItem e)
            {
                d.Account_Updating(e);
            }
            private static void __Account_Updated(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.AccountItem e)
            {
                d.Account_Updated(e);
            }
            private static void __Account_Deleting(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.AccountItem e)
            {
                d.Account_Deleting(e);
            }
            private static void __Account_Deleted(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.AccountItem e)
            {
                d.Account_Deleted(e);
            }
            private static void __Account_Validate(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.AccountItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Account_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.AccountItem, bool>> __Account_Filter(global::LightSwitchApplication.LightAppDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.AccountItem, bool>> filter = null;
                d.Account_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LightAppDataService, global::LightSwitchApplication.EventItem>
                __c_EventEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.LightAppDataService, global::LightSwitchApplication.EventItem>(
                    "c_Event",
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_CanInsert,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_CanUpdate,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_CanDelete,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_CanRead,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_Inserting,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_Inserted,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_Updating,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_Updated,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_Deleting,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_Deleted,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_Validate,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__c_Event_Filter);
            private static bool __c_Event_CanInsert(global::LightSwitchApplication.LightAppDataService d)
            {
                bool result = true;
                d.c_Event_CanInsert(ref result);
                return result;
            }
            private static bool __c_Event_CanUpdate(global::LightSwitchApplication.LightAppDataService d)
            {
                bool result = true;
                d.c_Event_CanUpdate(ref result);
                return result;
            }
            private static bool __c_Event_CanDelete(global::LightSwitchApplication.LightAppDataService d)
            {
                bool result = true;
                d.c_Event_CanDelete(ref result);
                return result;
            }
            private static bool __c_Event_CanRead(global::LightSwitchApplication.LightAppDataService d)
            {
                bool result = true;
                d.c_Event_CanRead(ref result);
                return result;
            }
            private static void __c_Event_Inserting(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.EventItem e)
            {
                d.c_Event_Inserting(e);
            }
            private static void __c_Event_Inserted(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.EventItem e)
            {
                d.c_Event_Inserted(e);
            }
            private static void __c_Event_Updating(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.EventItem e)
            {
                d.c_Event_Updating(e);
            }
            private static void __c_Event_Updated(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.EventItem e)
            {
                d.c_Event_Updated(e);
            }
            private static void __c_Event_Deleting(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.EventItem e)
            {
                d.c_Event_Deleting(e);
            }
            private static void __c_Event_Deleted(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.EventItem e)
            {
                d.c_Event_Deleted(e);
            }
            private static void __c_Event_Validate(global::LightSwitchApplication.LightAppDataService d, global::LightSwitchApplication.EventItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.c_Event_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.EventItem, bool>> __c_Event_Filter(global::LightSwitchApplication.LightAppDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.EventItem, bool>> filter = null;
                d.c_Event_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.LightAppDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.LightAppDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.LightAppDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.LightAppDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.LightAppDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.LightAppDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.LightAppDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.LightAppDataService>(
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.LightAppDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.LightAppDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.LightAppDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.LightAppDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
        }
    
        #endregion
    }
    
    #endregion
}
