
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// 初始化 DataWorkspace 的新实例。可以对新实例中的数据源进行更改，这些更改与对默认 DataWorkspace 中的数据源进行的更改无关。
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// 获取 LightAppData 数据源。这将提供要对该数据源中的数据进行查询和更新的成员。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.LightAppData LightAppData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.LightAppData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.LightAppData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.LightAppData> LightAppData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.LightAppData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.LightAppData>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.LightAppData>.Entry
                    LightAppData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.LightAppData>.Entry(
                        "LightAppData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._LightAppData_Stub);
                private static void _LightAppData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.LightAppData>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._LightAppData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.LightAppData>.Data _LightAppData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// 提供要对 LightAppData 数据源中的数据进行查询和更新的成员。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class LightAppData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// 此构造函数用于内部 LightSwitch 框架。请改用 DataWorkspace。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public LightAppData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// 获取 Account 实体集。该实体集提供要访问指定类型的实体的成员。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.AccountItem> Account
        {
            get
            {
                return global::LightSwitchApplication.LightAppData.DetailsClass.GetValue(this, global::LightSwitchApplication.LightAppData.DetailsClass.PropertySetProperties.Account);
            }
        }
        
        /// <summary>
        /// 获取 c_Event 实体集。该实体集提供要访问指定类型的实体的成员。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EventItem> c_Event
        {
            get
            {
                return global::LightSwitchApplication.LightAppData.DetailsClass.GetValue(this, global::LightSwitchApplication.LightAppData.DetailsClass.PropertySetProperties.c_Event);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// 返回参数指定的标识所对应的实体。
        /// </summary>
        /// <param name="ID">
        /// 要检索的实体的"ID"键属性的值。
        /// </param>
        public global::LightSwitchApplication.AccountItem Account_Single(global::System.Nullable<global::System.Guid> ID)
        {
            return this.Details.Methods.Account_Single.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// 返回参数指定的标识所对应的实体；如果不存在这样的实体，则返回 Null。
        /// </summary>
        /// <param name="ID">
        /// 要检索的实体的"ID"键属性的值。
        /// </param>
        public global::LightSwitchApplication.AccountItem Account_SingleOrDefault(global::System.Nullable<global::System.Guid> ID)
        {
            return this.Details.Methods.Account_SingleOrDefault.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// 返回参数指定的标识所对应的实体。
        /// </summary>
        /// <param name="ID">
        /// 要检索的实体的"ID"键属性的值。
        /// </param>
        public global::LightSwitchApplication.EventItem c_Event_Single(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.c_Event_Single.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// 返回参数指定的标识所对应的实体；如果不存在这样的实体，则返回 Null。
        /// </summary>
        /// <param name="ID">
        /// 要检索的实体的"ID"键属性的值。
        /// </param>
        public global::LightSwitchApplication.EventItem c_Event_SingleOrDefault(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.c_Event_SingleOrDefault.CreateInvocation(ID).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.LightAppData.DetailsClass.PropertySet, global::LightSwitchApplication.LightAppData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.LightAppData.DetailsClass.MethodSetProperties.Account_Single;
                var initializePropertyEntry = global::LightSwitchApplication.LightAppData.DetailsClass.PropertySetProperties.Account;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.LightAppData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.LightAppData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem> Account_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LightAppData.DetailsClass.MethodSetProperties.Account_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem> Account_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LightAppData.DetailsClass.MethodSetProperties.Account_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem> c_Event_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LightAppData.DetailsClass.MethodSetProperties.c_Event_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem> c_Event_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LightAppData.DetailsClass.MethodSetProperties.c_Event_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem> Account
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LightAppData.DetailsClass.PropertySetProperties.Account) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem> c_Event
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LightAppData.DetailsClass.PropertySetProperties.c_Event) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Entry
                    Account_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Entry(
                        "Account_Single",
                        global::LightSwitchApplication.LightAppData.DetailsClass.MethodSetProperties._Account_Single_Stub);
                private static void _Account_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LightAppData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Data> c, global::LightSwitchApplication.LightAppData.DetailsClass d, object sf)
                {
                    c(d, ref d._Account_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Entry
                    Account_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Entry(
                        "Account_SingleOrDefault",
                        global::LightSwitchApplication.LightAppData.DetailsClass.MethodSetProperties._Account_SingleOrDefault_Stub);
                private static void _Account_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LightAppData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Data> c, global::LightSwitchApplication.LightAppData.DetailsClass d, object sf)
                {
                    c(d, ref d._Account_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Entry
                    c_Event_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Entry(
                        "c_Event_Single",
                        global::LightSwitchApplication.LightAppData.DetailsClass.MethodSetProperties._c_Event_Single_Stub);
                private static void _c_Event_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LightAppData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Data> c, global::LightSwitchApplication.LightAppData.DetailsClass d, object sf)
                {
                    c(d, ref d._c_Event_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Entry
                    c_Event_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Entry(
                        "c_Event_SingleOrDefault",
                        global::LightSwitchApplication.LightAppData.DetailsClass.MethodSetProperties._c_Event_SingleOrDefault_Stub);
                private static void _c_Event_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LightAppData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Data> c, global::LightSwitchApplication.LightAppData.DetailsClass d, object sf)
                {
                    c(d, ref d._c_Event_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Entry
                    Account = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Entry(
                        "Account",
                        global::LightSwitchApplication.LightAppData.DetailsClass.PropertySetProperties._Account_Stub);
                private static void _Account_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LightAppData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Data> c, global::LightSwitchApplication.LightAppData.DetailsClass d, object sf)
                {
                    c(d, ref d._Account, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Entry
                    c_Event = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Entry(
                        "c_Event",
                        global::LightSwitchApplication.LightAppData.DetailsClass.PropertySetProperties._c_Event_Stub);
                private static void _c_Event_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LightAppData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Data> c, global::LightSwitchApplication.LightAppData.DetailsClass d, object sf)
                {
                    c(d, ref d._c_Event, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Data _Account;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Data _c_Event;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Data _Account_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.AccountItem>.Data _Account_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Data _c_Event_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.LightAppData, global::LightSwitchApplication.LightAppData.DetailsClass, global::LightSwitchApplication.EventItem>.Data _c_Event_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
