

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// 没有可用的模块化说明
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class AccountItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// 初始化 AccountItem 实体的新实例。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public AccountItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public AccountItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.AccountItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.AccountItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AccountItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AccountItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// 获取此应用程序的 Application 对象。Application 对象可提供对活动屏幕的访问权限、用于打开屏幕的方法以及对当前用户的访问权限。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// 获取包含数据工作区。该数据工作区可提供对应用程序中所有数据源的访问权限。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// 没有可用的模块化说明
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return global::LightSwitchApplication.AccountItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.ID);
            }
            set
            {
                global::LightSwitchApplication.AccountItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.ID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// 没有可用的模块化说明
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.AccountItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.AccountItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// 没有可用的模块化说明
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime JoinDate
        {
            get
            {
                return global::LightSwitchApplication.AccountItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.JoinDate);
            }
            set
            {
                global::LightSwitchApplication.AccountItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.JoinDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JoinDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JoinDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JoinDate_Changed();

        /// <summary>
        /// 没有可用的模块化说明
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Status
        {
            get
            {
                return global::LightSwitchApplication.AccountItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.Status);
            }
            set
            {
                global::LightSwitchApplication.AccountItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.Status, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Changed();

        /// <summary>
        /// 没有可用的模块化说明
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EventItem> c_Event
        {
            get
            {
                return global::LightSwitchApplication.AccountItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.c_Event);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EventItem> c_EventQuery
        {
            get
            {
                return global::LightSwitchApplication.AccountItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.c_Event);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.AccountItem,
                global::LightSwitchApplication.AccountItem.DetailsClass,
                global::LightSwitchApplication.AccountItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.AccountItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass>.Entry
                __AccountItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.AccountItem.DetailsClass.__AccountItem_CreateNew,
                    global::LightSwitchApplication.AccountItem.DetailsClass.__AccountItem_Created,
                    global::LightSwitchApplication.AccountItem.DetailsClass.__AccountItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.AccountItem __AccountItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.AccountItem> es)
            {
                return new global::LightSwitchApplication.AccountItem(es);
            }
            private static void __AccountItem_Created(global::LightSwitchApplication.AccountItem e)
            {
                e.AccountItem_Created();
            }
            private static bool __AccountItem_AllowSaveWithErrors(global::LightSwitchApplication.AccountItem e)
            {
                bool result = false;
                e.AccountItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.AccountItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.Guid> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.DateTime> JoinDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.JoinDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, bool> Status
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.Status) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::LightSwitchApplication.EventItem> c_Event
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.c_Event) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::LightSwitchApplication.EventItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Guid ID { get; set; }
                new string Name { get; set; }
                new global::System.DateTime JoinDate { get; set; }
                new bool Status { get; set; }
                new global::System.Collections.IEnumerable c_Event { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.Guid>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.Guid>.Entry(
                        "ID",
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._ID_SetImplementationValue,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AccountItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.AccountItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.AccountItem e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.AccountItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static global::System.Guid _ID_GetImplementationValue(global::LightSwitchApplication.AccountItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_SetImplementationValue(global::LightSwitchApplication.AccountItem.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.ID = v;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.AccountItem e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AccountItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AccountItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.AccountItem e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.AccountItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.AccountItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.AccountItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.AccountItem e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.DateTime>.Entry
                    JoinDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.DateTime>.Entry(
                        "JoinDate",
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._JoinDate_Stub,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._JoinDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._JoinDate_Validate,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._JoinDate_GetImplementationValue,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._JoinDate_SetImplementationValue,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._JoinDate_OnValueChanged);
                private static void _JoinDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AccountItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.AccountItem.DetailsClass d, object sf)
                {
                    c(d, ref d._JoinDate, sf);
                }
                private static bool _JoinDate_ComputeIsReadOnly(global::LightSwitchApplication.AccountItem e)
                {
                    bool result = false;
                    e.JoinDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _JoinDate_Validate(global::LightSwitchApplication.AccountItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.JoinDate_Validate(r);
                }
                private static global::System.DateTime _JoinDate_GetImplementationValue(global::LightSwitchApplication.AccountItem.DetailsClass d)
                {
                    return d.ImplementationEntity.JoinDate;
                }
                private static void _JoinDate_SetImplementationValue(global::LightSwitchApplication.AccountItem.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.JoinDate = global::LightSwitchApplication.AccountItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _JoinDate_OnValueChanged(global::LightSwitchApplication.AccountItem e)
                {
                    e.JoinDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, bool>.Entry
                    Status = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, bool>.Entry(
                        "Status",
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Status_Stub,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Status_ComputeIsReadOnly,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Status_Validate,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Status_GetImplementationValue,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Status_SetImplementationValue,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._Status_OnValueChanged);
                private static void _Status_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AccountItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, bool>.Data> c, global::LightSwitchApplication.AccountItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Status, sf);
                }
                private static bool _Status_ComputeIsReadOnly(global::LightSwitchApplication.AccountItem e)
                {
                    bool result = false;
                    e.Status_IsReadOnly(ref result);
                    return result;
                }
                private static void _Status_Validate(global::LightSwitchApplication.AccountItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Status_Validate(r);
                }
                private static bool _Status_GetImplementationValue(global::LightSwitchApplication.AccountItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Status;
                }
                private static void _Status_SetImplementationValue(global::LightSwitchApplication.AccountItem.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.Status = v;
                }
                private static void _Status_OnValueChanged(global::LightSwitchApplication.AccountItem e)
                {
                    e.Status_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::LightSwitchApplication.EventItem>.Entry
                    c_Event = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::LightSwitchApplication.EventItem>.Entry(
                        "c_Event",
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._c_Event_Stub,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._c_Event_GetReferencedEntities,
                        global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties._c_Event_GetEntityCollection);
                private static void _c_Event_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AccountItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::LightSwitchApplication.EventItem>.Data> c, global::LightSwitchApplication.AccountItem.DetailsClass d, object sf)
                {
                    c(d, ref d._c_Event, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EventItem> _c_Event_GetReferencedEntities(global::LightSwitchApplication.AccountItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EventItem, global::LightSwitchApplication.EventItem.DetailsClass>(global::LightSwitchApplication.AccountItem.DetailsClass.PropertySetProperties.c_Event, ref d._c_Event);
                }
                private static global::System.Collections.IEnumerable _c_Event_GetEntityCollection(global::LightSwitchApplication.AccountItem.DetailsClass d)
                {
                    return d.ImplementationEntity.c_Event;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.Guid>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::System.DateTime>.Data _JoinDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, bool>.Data _Status;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AccountItem, global::LightSwitchApplication.AccountItem.DetailsClass, global::LightSwitchApplication.EventItem>.Data _c_Event;
            
        }
    
        #endregion
    }
    
    #endregion
}
