//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region AccountItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/LightAppData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AccountItem :
        global::LightSwitchApplication.AccountItem.DetailsClass.IImplementation
    {
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnJoinDateChanged()
        {
            this.___OnPropertyChanged("JoinDate");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.AccountItem.DetailsClass.IImplementation.c_Event
        {
            get
            {
                return this.c_Event;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EventItem> __c_Event
        {
            get
            {
                if (this.___c_Event == null)
                {
                    this.___c_Event = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EventItem>(
                        this,
                        "c_Event",
                        () => this._c_Event,
                        e => global::System.Object.Equals(e.Aid, this.ID));
                }
                return this.___c_Event;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EventItem> ___c_Event;
        
    }
    #endregion
    
    #region EventItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/LightAppData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EventItem :
        global::LightSwitchApplication.EventItem.DetailsClass.IImplementation
    {
        partial void OnAidChanged()
        {
            this.___OnPropertyChanged("Aid");
            this.___OnPropertyChanged("AccountItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnTopicChanged()
        {
            this.___OnPropertyChanged("Topic");
        }
        
        partial void OnDetailChanged()
        {
            this.___OnPropertyChanged("Detail");
        }
        
        partial void OnLanuchChanged()
        {
            this.___OnPropertyChanged("Lanuch");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EventItem.DetailsClass.IImplementation.AccountItem
        {
            get
            {
                return this.AccountItem;
            }
            set
            {
                this.AccountItem = (global::LightSwitchApplication.Implementation.AccountItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AccountItem> __AccountItem
        {
            get
            {
                if (this.___AccountItem == null)
                {
                    this.___AccountItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AccountItem>(
                        this,
                        "AccountItem",
                        new string[] { "Aid" },
                        e => global::System.Object.Equals(e.ID, this.Aid),
                        () => this._AccountItem,
                        e => this._AccountItem = e);
                }
                return this.___AccountItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AccountItem> ___AccountItem;
        
    }
    #endregion
    
    #region LightAppDataObjectContext
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class LightAppDataObjectContext
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.AccountItem))
            {
                return new global::LightSwitchApplication.Implementation.AccountItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EventItem))
            {
                return new global::LightSwitchApplication.Implementation.EventItem();
            }
            return null;
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.LightAppData))
            {
                return new global::LightSwitchApplication.LightAppData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.LightAppData))
            {
                return new global::LightSwitchApplication.Implementation.LightAppDataObjectContext(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../LightAppData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.AccountItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AccountItem);
            }
            if (typeof(global::LightSwitchApplication.EventItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EventItem);
            }
            return null;
        }
    }
}
