//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 原始文件名:
// 生成日期: 2014-04-28 16:08:37
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// 架构中不存在 LightAppDataObjectContext 的注释。
    /// </summary>
    public partial class LightAppDataObjectContext : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// 初始化新的 LightAppDataObjectContext 对象。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public LightAppDataObjectContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("LightSwitchApplication", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("LightSwitchApplication.Implementation", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// 架构中不存在 Account 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AccountItem> Account
        {
            get
            {
                if ((this._Account == null))
                {
                    this._Account = base.CreateQuery<AccountItem>("Account");
                }
                return this._Account;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AccountItem> _Account;
        /// <summary>
        /// 架构中不存在 c_Event 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<EventItem> c_Event
        {
            get
            {
                if ((this._c_Event == null))
                {
                    this._c_Event = base.CreateQuery<EventItem>("c_Event");
                }
                return this._c_Event;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<EventItem> _c_Event;
        /// <summary>
        /// 架构中不存在 Account 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAccount(AccountItem accountItem)
        {
            base.AddObject("Account", accountItem);
        }
        /// <summary>
        /// 架构中不存在 c_Event 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToc_Event(EventItem eventItem)
        {
            base.AddObject("c_Event", eventItem);
        }
    }
    /// <summary>
    /// 架构中不存在 LightSwitchApplication.AccountItem 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Account")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class AccountItem : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 AccountItem 对象。
        /// </summary>
        /// <param name="ID">ID 的初始值。</param>
        /// <param name="name">Name 的初始值。</param>
        /// <param name="joinDate">JoinDate 的初始值。</param>
        /// <param name="status">Status 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AccountItem CreateAccountItem(global::System.Guid ID, string name, global::System.DateTime joinDate, bool status)
        {
            AccountItem accountItem = new AccountItem();
            accountItem.ID = ID;
            accountItem.Name = name;
            accountItem.JoinDate = joinDate;
            accountItem.Status = status;
            return accountItem;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                if (object.Equals(this.ID, value))
                {
                    return;
                }
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 JoinDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime JoinDate
        {
            get
            {
                return this._JoinDate;
            }
            set
            {
                this.OnJoinDateChanging(value);
                if (object.Equals(this.JoinDate, value))
                {
                    return;
                }
                this._JoinDate = value;
                this.OnJoinDateChanged();
                this.OnPropertyChanged("JoinDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _JoinDate;
        partial void OnJoinDateChanging(global::System.DateTime value);
        partial void OnJoinDateChanged();
        /// <summary>
        /// 架构中不存在属性 Status 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                if (object.Equals(this.Status, value))
                {
                    return;
                }
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Status;
        partial void OnStatusChanging(bool value);
        partial void OnStatusChanged();
        /// <summary>
        /// 架构中不存在 c_Event 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<EventItem> c_Event
        {
            get
            {
                this.@__c_Event.EnsureValueInitialized();
                return this._c_Event;
            }
            set
            {
                this._c_Event = value;
                this.OnPropertyChanged("c_Event");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<EventItem> _c_Event = new global::System.Data.Services.Client.DataServiceCollection<EventItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 LightSwitchApplication.EventItem 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("c_Event")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class EventItem : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 EventItem 对象。
        /// </summary>
        /// <param name="ID">ID 的初始值。</param>
        /// <param name="topic">Topic 的初始值。</param>
        /// <param name="detail">Detail 的初始值。</param>
        /// <param name="lanuch">Lanuch 的初始值。</param>
        /// <param name="status">Status 的初始值。</param>
        /// <param name="aid">Aid 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EventItem CreateEventItem(int ID, string topic, string detail, global::System.DateTime lanuch, int status, global::System.Guid aid)
        {
            EventItem eventItem = new EventItem();
            eventItem.ID = ID;
            eventItem.Topic = topic;
            eventItem.Detail = detail;
            eventItem.Lanuch = lanuch;
            eventItem.Status = status;
            eventItem.Aid = aid;
            return eventItem;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                if (object.Equals(this.ID, value))
                {
                    return;
                }
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 Topic 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Topic
        {
            get
            {
                return this._Topic;
            }
            set
            {
                this.OnTopicChanging(value);
                if (object.Equals(this.Topic, value))
                {
                    return;
                }
                this._Topic = value;
                this.OnTopicChanged();
                this.OnPropertyChanged("Topic");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Topic;
        partial void OnTopicChanging(string value);
        partial void OnTopicChanged();
        /// <summary>
        /// 架构中不存在属性 Detail 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Detail
        {
            get
            {
                return this._Detail;
            }
            set
            {
                this.OnDetailChanging(value);
                if (object.Equals(this.Detail, value))
                {
                    return;
                }
                this._Detail = value;
                this.OnDetailChanged();
                this.OnPropertyChanged("Detail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Detail;
        partial void OnDetailChanging(string value);
        partial void OnDetailChanged();
        /// <summary>
        /// 架构中不存在属性 Lanuch 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Lanuch
        {
            get
            {
                return this._Lanuch;
            }
            set
            {
                this.OnLanuchChanging(value);
                if (object.Equals(this.Lanuch, value))
                {
                    return;
                }
                this._Lanuch = value;
                this.OnLanuchChanged();
                this.OnPropertyChanged("Lanuch");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Lanuch;
        partial void OnLanuchChanging(global::System.DateTime value);
        partial void OnLanuchChanged();
        /// <summary>
        /// 架构中不存在属性 Status 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                if (object.Equals(this.Status, value))
                {
                    return;
                }
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
        /// <summary>
        /// 架构中不存在属性 Aid 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Aid
        {
            get
            {
                return this._Aid;
            }
            set
            {
                this.OnAidChanging(value);
                if (object.Equals(this.Aid, value))
                {
                    return;
                }
                this._Aid = value;
                this.OnAidChanged();
                this.OnPropertyChanged("Aid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Aid;
        partial void OnAidChanging(global::System.Guid value);
        partial void OnAidChanged();
        /// <summary>
        /// 架构中不存在 AccountItem 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public AccountItem AccountItem
        {
            get
            {
                this.@__AccountItem.EnsureValueInitialized();
                return this._AccountItem;
            }
            set
            {
                AccountItem previous = this.AccountItem;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._AccountItem = null;
                    this.@__AccountItem.OnValueSet();
                    previous.c_Event.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Aid = value.ID;
                    }
                    else
                    {
                        this.Aid = default(global::System.Guid);
                    }
                }
                this._AccountItem = value;
                this.@__AccountItem.OnValueSet();
                if ((value != null))
                {
                    value.@__c_Event.Add(this);
                }
                this.___OnPropertyChanged("AccountItem");
                this.OnPropertyChanged("AccountItem");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private AccountItem _AccountItem;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
