//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class c_EventListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private c_EventListDetail() : base("LightSwitchApplication:c_EventListDetail")
        {
            global::LightSwitchApplication.c_EventListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static c_EventListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.c_EventListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_EventListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_EventListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_EventListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_EventListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_EventListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_EventListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_EventListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// 获取此应用程序的 Application 对象。Application 对象可提供对活动屏幕的访问权限、用于打开屏幕的方法以及对当前用户的访问权限。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// 获取包含数据工作区。该数据工作区可提供对应用程序中所有数据源的访问权限。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void c_Event_SelectionChanged();

        partial void c_Event_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_Loaded(bool succeeded);

        /// <summary>
        /// 获取 c_Event 视觉集合。该集合包含当前显示在各个列表或网格控件中的所有记录。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.EventItem> c_Event
        {
            get
            {
                return global::LightSwitchApplication.c_EventListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySetProperties.c_Event);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Event_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass, global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.c_EventListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.c_EventListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySetProperties.c_Event;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass>.Entry
                __c_EventListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.c_EventListDetail.DetailsClass.__c_EventListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.c_EventListDetail.DetailsClass.__c_EventListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.c_EventListDetail.DetailsClass.__c_EventListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.c_EventListDetail.DetailsClass.__c_EventListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.c_EventListDetail.DetailsClass.__c_EventListDetail_InvokeCreated,
                    global::LightSwitchApplication.c_EventListDetail.DetailsClass.__c_EventListDetail_InvokeActivated,
                    global::LightSwitchApplication.c_EventListDetail.DetailsClass.__c_EventListDetail_InvokeSaveErrorEvent);
            private static void __c_EventListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.c_EventListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.c_EventListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __c_EventListDetail_InvokeSavingEvent(global::LightSwitchApplication.c_EventListDetail s)
            {
                bool handled = false;
                s.c_EventListDetail_Saving(ref handled);
                return handled;
            }
            private static void __c_EventListDetail_InvokeSavedEvent(global::LightSwitchApplication.c_EventListDetail s)
            {
                s.c_EventListDetail_Saved();
            }
            private static bool __c_EventListDetail_InvokeClosingEvent(global::LightSwitchApplication.c_EventListDetail s)
            {
                bool cancel = false;
                s.c_EventListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __c_EventListDetail_InvokeCreated(global::LightSwitchApplication.c_EventListDetail s)
            {
                s.c_EventListDetail_Created();
            }
            private static void __c_EventListDetail_InvokeActivated(global::LightSwitchApplication.c_EventListDetail s)
            {
                s.c_EventListDetail_Activated();
            }
            private static bool __c_EventListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.c_EventListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.c_EventListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.c_EventListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.c_EventListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable c_EventQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    this.Screen.DataWorkspace.LightAppData.c_Event,
                    "AccountItem");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass, global::LightSwitchApplication.EventItem>.Data _c_Event;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass, global::LightSwitchApplication.EventItem> c_Event
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass, global::LightSwitchApplication.EventItem>)base.GetItem(global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySetProperties.c_Event);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass, global::LightSwitchApplication.EventItem>.Entry
                    c_Event = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass, global::LightSwitchApplication.EventItem>.Entry(
                        "c_Event",
                        global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySetProperties._c_Event_Stub,
                        global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySetProperties._c_Event_Validate,
                        global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySetProperties._c_Event_CreateQuery,
                        global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySetProperties._c_Event_SelectionChanged,
                        global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySetProperties._c_Event_OnCollectionChanged,
                        global::LightSwitchApplication.c_EventListDetail.DetailsClass.PropertySetProperties._c_Event_OnLoaded);
                private static void _c_Event_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.c_EventListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.c_EventListDetail, global::LightSwitchApplication.c_EventListDetail.DetailsClass, global::LightSwitchApplication.EventItem>.Data> c, global::LightSwitchApplication.c_EventListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._c_Event, sf);
                }
                private static void _c_Event_Validate(global::LightSwitchApplication.c_EventListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.c_Event_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _c_Event_CreateQuery(global::LightSwitchApplication.c_EventListDetail.DetailsClass d, object[] args)
                {
                    return d.c_EventQuery();
                }
                private static void _c_Event_SelectionChanged(global::LightSwitchApplication.c_EventListDetail s)
                {
                    s.c_Event_SelectionChanged();
                }
                private static void _c_Event_OnCollectionChanged(global::LightSwitchApplication.c_EventListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.c_Event_Changed(e);
                }
                private static void _c_Event_OnLoaded(global::LightSwitchApplication.c_EventListDetail s, bool succeeded)
                {
                    s.c_Event_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
